config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/sign-up' => 'registrations#new'
  post '/sign-up' => 'registrations#create'
  get '/sign-out' => 'authentication#destroy'
  get '/sign-in' => 'authentication#new'
  post '/sign-in' => 'authentication#create'

  resources :users
  resources :wineriez
  resources :winez

  resources :regions do
    resources :region_comments
    resources :wineries do
      resources :winery_comments
      resources :wines do
        resources :wine_comments
      end
    end
  end
end

app/controllers/winez_controller.rb
class WinezController < ApplicationController

  def index
    @wines = current_user.wines
    @wineries = current_user.wineries
    @region = current_user.regions
  end

end

app/views/winez/index.html.haml
.container
  =link_to "HOME", "/", class: "btn btn-success margin-top-button pull-right"

  %h1
    = "#{current_user.full_name}'s Complete Wine List"

    %table.table
      %thead
        %tr
          %th Wine Name
          %th Grape Type
          %th Taste
          %th Bottle Rating
          %th Year Bottled
          %th Winery Name
          %th Number of Bottles
      %tbody


      %tbody
        - @wineries.each do |winery|
          - winery.wines.each do |wine|
            - @region.each do |region|
              %tr
                %td
                  = link_to wine.bottle_name, region_winery_wines_path(region, winery)
                %td
                  = wine.grape_type
                %td
                  = wine.taste
                %td
                  = wine.bottle_rating
                %td
                  = wine.bottle_year
                %td
                  = wine.winery_name
                %td
                  = wine.amount
                %td
                  = link_to "Delete", region_winery_path(region, winery, wine), class: "btn btn-danger pull-right",  method: :delete
                  = link_to "Edit Wine", edit_region_winery_path(region, winery, wine), class: "btn btn-primary pull-right"