config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/sign-up' => 'registrations#new'
  post '/sign-up' => 'registrations#create'
  get '/sign-out' => 'authentication#destroy'
  get '/sign-in' => 'authentication#new'
  post '/sign-in' => 'authentication#create'

  resources :users
  resources :wineriez
  resources :winez

  resources :regions do
    resources :region_comments
    resources :wineries do
      resources :winery_comments
      resources :wines do
        resources :wine_comments
      end
    end
  end
end

app/models/region.rb
class Region < ActiveRecord::Base

  belongs_to :user

  has_many :wineries
  has_many :region_comments
  has_many :winery_comments
  has_many :wine_comments
  

  def location
    "#{state}, #{country}"
  end
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
before_action :get_all_wineries



  def index
    @regions = current_user.regions
  end

  def new
    @region = Region.new
  end

  def create
    @region = Region.new(region_params)
    @region.save
    flash[:notice] = "New Winery Added!"
    redirect_to region_path(@region)
  end

  def show
    @region = Region.find(params[:id])
    @region_comment = RegionComment.new
  end

  def edit
    @region = Region.find(params[:id])
  end

  def update
    @region = Region.find(params[:id])
    if @region.update(region_params)
      flash[:notice] = "Region successfully updated"
      redirect_to regions_path
    else
      render :edit
    end
  end


  def destroy
    region = Region.find(params[:id])
    region.destroy
    redirect_to regions_path
    flash[:notice] = "The Region has been successfully deleted"
  end

private

  def region_params
    params.require(:region).permit(:region_name, :country, :state).merge(:user_id => current_user.id)
  end

  def get_all_wineries
    @wineries = Winery.all
  end


end

app/views/regions/edit.html.haml
.container
  .page-header
    %h2 #{current_user.full_name}, Add a New Region to Your Inventory
    = form_for @region do |f|

      .form-group

        = f.label :region_name, class: "control-label"
        = f.text_field :region_name, class: "form-control"

      .form-group

        = f.label :state, class: "control-label"
        = f.text_field :state, class: "form-control"
      %br

      .form-group

        = f.label :country, class: "control-label"
        = f.text_field :country, class: "form-control"
      %br

      .form-group

        = f.submit

app/views/regions/index.html.haml
.container
  =link_to "Add New Region", new_region_path, class: "btn btn-danger margin-top-button pull-right"
  =link_to "HOME", "/", class: "btn btn-success margin-top-button pull-right"

  %h1
    #{current_user.full_name}'s Regions
  %table.table
    %thead
      %tr
        %th
          Region Name
        %th{colspan:2}
          Region State
        %th
          Region Country
        %th
    %tbody
      - @regions.each do |region|
        %tr
          %td
            = link_to region.region_name, region_path(region)
          %td
            = region.state
          %td
          
            = region.country
          %td
            = link_to "Delete Region", region_path(region), class: "btn btn-danger pull-right",  method: :delete
            = link_to "Edit Region", edit_region_path(region), class: "btn btn-primary pull-right"

app/views/regions/new.html.haml
.container
  .page-header
    %h2 #{current_user.full_name}, Add a New Region to Your Inventory
    = form_for @region do |f|

      .form-group

        = f.label :region_name, class: "control-label"
        = f.text_field :region_name, class: "form-control"

      .form-group

        = f.label :state, class: "control-label"
        = f.text_field :state, class: "form-control"
      %br

      .form-group

        = f.label :country, class: "control-label"
        = f.text_field :country, class: "form-control"
      %br

      .form-group

        = f.submit

app/views/regions/show.html.haml
.container
  .page-header
    = link_to "Go Back", regions_path, class: "btn btn-info pull-right"
    = link_to "Delete Region", region_path(@region), method: :delete, data: {confirm: "Are you sure"}, class: "btn btn-primary pull-right"
    = link_to "Edit Region Information", edit_region_path(@region), class: "btn btn-danger pull-right"
    %h1
      = link_to "Add New Winery to Region", new_region_winery_path(@region), class: "btn btn-warning pull-right"
    %h3
      = @region.location
      = @region.region_name

  %h2 Region Comments
  .comments
    - @region.region_comments.each do |comment|
      .row
        .col-md-3
          .row
            .col-md-12
              = link_to @region_comments
          .row
            .col-md-12.txt-muted
              = time_ago_in_words(comment.created_at) + " ago"
        .col-md-9
          %p= comment.content
        %br

  = form_for [@region, @region_comment], html: {class: 'form-horizontal'} do |f|
    .form-group
      .col-md-offset-3.col-md-9
        = f.text_area :content, class: 'form-control'
    .form-group
      .col-md-offset-3.col-md-7
        = f.submit 'Add Comment', class: 'btn btn-primary'