config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/sign-up' => 'registrations#new'
  post '/sign-up' => 'registrations#create'
  get '/sign-out' => 'authentication#destroy'
  get '/sign-in' => 'authentication#new'
  post '/sign-in' => 'authentication#create'

  resources :users
  resources :wineriez
  resources :winez

  resources :regions do
    resources :region_comments
    resources :wineries do
      resources :winery_comments
      resources :wines do
        resources :wine_comments
      end
    end
  end
end

app/models/wine.rb
class Wine < ActiveRecord::Base
  belongs_to :user
  belongs_to :winery
  has_many :wine_comments



end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :find_region
  before_action :find_winery
  # before_action :get_all_regions
  # before_action :get_all_wineries

def index
  @wines = current_user.wines
end

def new
  @wine = Wine.new
end

def create
  @wine = @winery.wines.new(wine_params)
  @wine.save
  flash[:notice] = "New Wine Added!"
  redirect_to region_winery_wines_path
end

def destroy
  @wine = Wine.find(params[:id])
  @wine.destroy
  redirect_to region_winery_wines_path
  flash[:notice] = "Wine has been deleted"
end

def edit
  @wine = Wine.find(params[:id])
end

def update
  @wine = Wine.find(params[:id])
  if @wine.update(wine_params)
    redirect_to region_winery_wines_path(@region, @winery)
    flash[:notice] = "You have updated"
  end
end

def show
  @wine = Wine.find(params[:id])
end


private

  def wine_params
    params.require(:wine).permit(:bottle_name, :bottle_year, :taste, :grape_type, :bottle_rating, :price, :amount, :winery_name)
  end


  def find_region
    @region = Region.find(params[:region_id])
  end

  def find_winery
    @winery = Winery.find(params[:winery_id])
  end

  def get_all_regions
    @regions = Region.all
  end

  def get_all_wineries
    @wineries = Winery.all
  end
end

app/views/wines/edit.html.haml
.container
  .page-header
    %h2 #{current_user.full_name}, Add a New Wine to Your Inventory
  = form_for [@region, @winery, @wine] do |f|

    .form-group

      = f.label :bottle_name, class: "control-label"
      = f.text_field :bottle_name, class: "form-control"
    %br

    .form-group

      = f.label :bottle_year, class: "control-label"
      = f.text_field :bottle_year, class: "form-control"
    %br

    .form-group

      = f.label :grape_type, class: "control-label"
      = f.text_field :grape_type, class: "form-control"
    %br

    .form-group

      = f.label :bottle_rating, class: "control-label"
      = f.text_field :bottle_rating, class: "form-control"

    %br

    .form-group
      = f.label :taste, class: "control-label"
      = f.text_field :taste, class: "form-control"
    %br

    .form-group
      = f.label :price, class: "control-label"
      = f.number_field :price, class: "form-control"

    %br

    .form-group
      = f.label :winery_name, class: "control-label"
      = f.text_field :winery_name, class: "form-control"

    %br

    .form-group
      = f.label :amount, class: "control-label"
      = f.number_field :amount, class: "form-control"

    .form-group

      = f.submit class: "btn btn-danger"
      = link_to "Cancel", region_winery_wines_path, class: "btn btn-success"

app/views/wines/index.html.haml
.container
  =link_to "Add New Wine", new_region_winery_wine_path, class: "btn btn-warning margin-top-button pull-right"
  = link_to "Back to Winery", region_wineries_path, class: "btn btn-info margin-top-button pull-right"
  %h1
    = "#{current_user.full_name}'s Wine List for the Region of #{@region.region_name} "

  %table.table
    %thead
      %tr
        %th Wine Name
        %th Grape Type
        %th Taste
        %th Bottle Rating
        %th Year Bottled
        %th Winery Name
        %th Number of Bottles
    %tbody
      - @wines.each do |wine|

        %tr
          %td
            = link_to wine.bottle_name, region_winery_wine_path(@region, @winery, wine)
          %td
            = wine.grape_type
          %td
            = wine.taste
          %td
            = wine.bottle_rating
          %td
            = wine.bottle_year
          %td
            = wine.winery_name
          %td
            = wine.amount
          %td
            = link_to "Delete Wine", region_winery_wine_path(@region, @winery, wine), method: :delete, data: {confirm: "You Sure?"}, class: "btn btn-danger"
          %td
            = link_to "Edit Wine Information", edit_region_winery_wine_path(@region, @winery, wine), class: "btn btn-success"

app/views/wines/new.html.haml
.container
  .page-header
    %h2 #{current_user.full_name}, Add a New Wine to Your Inventory
  = form_for [@region, @winery, @wine] do |f|

    .form-group

      = f.label :bottle_name, class: "control-label"
      = f.text_field :bottle_name, class: "form-control"
    %br

    .form-group

      = f.label :bottle_year, class: "control-label"
      = f.text_field :bottle_year, class: "form-control"
    %br

    .form-group

      = f.label :grape_type, class: "control-label"
      = f.text_field :grape_type, class: "form-control"
    %br

    .form-group

      = f.label :bottle_rating, class: "control-label"
      = f.text_field :bottle_rating, class: "form-control"

    %br

    .form-group
      = f.label :taste, class: "control-label"
      = f.text_field :taste, class: "form-control"
    %br

    .form-group
      = f.label :price, class: "control-label"
      = f.number_field :price, class: "form-control"

    %br

    .form-group
      = f.label :winery_name, class: "control-label"
      = f.text_field :winery_name, class: "form-control"

    %br

    .form-group
      = f.label :amount, class: "control-label"
      = f.number_field :amount, class: "form-control"

    .form-group

      = f.submit class: "btn btn-danger"
      = link_to "Cancel", region_winery_wines_path, class: "btn btn-success"

app/views/wines/show.html.haml
.container
  .page-header
    %h1
      ="#{current_user.full_name} "
      = link_to "Edit Wine Information", edit_region_winery_wine_path(@region, @winery, @wine), class: "btn btn-danger pull-right"
      = link_to "Delete Wine",  region_winery_wine_path(@region, @winery, @wine), method: :delete, data: {confirm: "You Sure?"}, class: "btn btn-primary pull-right"

      = link_to "Go Back", region_winery_wines_path(@region, @winery), class: "btn btn-primary pull-right"
  %h2
    = link_to "#{@region.region_name} Region", regions_path
    %br
    = link_to "#{@winery.winery_name} Winery", region_wineries_path(@region)
    %h3
      = "#{@wine.bottle_name} Wine"
      %br
      %br
      = "#{@wine.grape_type} Grapes"
      %br
      %br
      = "#{@wine.taste}"
      %br
      %br
      = "#{@wine.bottle_rating} out of 100"
      %br
      %br
      = "Bottled in #{@wine.bottle_year}"
      %br
      %br
      = "Bottled at #{@wine.winery.winery_name} Winery"
      %br
      %br
      = "#{@wine.amount} Bottles Left"