config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/sign-up' => 'registrations#new'
  post '/sign-up' => 'registrations#create'
  get '/sign-out' => 'authentication#destroy'
  get '/sign-in' => 'authentication#new'
  post '/sign-in' => 'authentication#create'

  resources :users
  resources :wineriez
  resources :winez

  resources :regions do
    resources :region_comments
    resources :wineries do
      resources :winery_comments
      resources :wines do
        resources :wine_comments
      end
    end
  end
end

app/views/layouts/application.html.haml
%html
  %head
    %title WineoApp
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

%body
  %nav.navbar.navbar-default.navbar-fixed-top
    .container
      %ul.nav.navbar-nav.navbar-right
        -if current_user
          %li= link_to "#{current_user.first_name} #{current_user.last_name}", users_path
          %li= link_to 'Sign Out', sign_out_path
        -else
          %li= link_to 'Sign Up', sign_up_path
          %li= link_to 'Sign In', sign_in_path


      = link_to "All Regions", regions_path, class:"navbar-brand"


      = link_to "All Wineries", wineriez_index_path, class:"navbar-brand"

      = link_to "All Wines", winez_index_path, class:"navbar-brand"

      = link_to ""








.container
  - if flash[:notice]
    .alert.alert-success= flash[:notice]

  - if flash[:error]
    .alert.alert-danger= flash[:error]
= yield